# Generated by Django 5.0.6 on 2024-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='Код проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('partnumber', models.CharField(max_length=200, verbose_name='Артикул')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('projects', models.ManyToManyField(to='app.project')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименование',
            },
        ),
    ]
